// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: wearable/v1/wearable_service.proto

package wearablepb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LiveMonitorRequest_Command int32

const (
	LiveMonitorRequest_START LiveMonitorRequest_Command = 0
	LiveMonitorRequest_PAUSE LiveMonitorRequest_Command = 1
	LiveMonitorRequest_STOP  LiveMonitorRequest_Command = 2
)

// Enum value maps for LiveMonitorRequest_Command.
var (
	LiveMonitorRequest_Command_name = map[int32]string{
		0: "START",
		1: "PAUSE",
		2: "STOP",
	}
	LiveMonitorRequest_Command_value = map[string]int32{
		"START": 0,
		"PAUSE": 1,
		"STOP":  2,
	}
)

func (x LiveMonitorRequest_Command) Enum() *LiveMonitorRequest_Command {
	p := new(LiveMonitorRequest_Command)
	*p = x
	return p
}

func (x LiveMonitorRequest_Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LiveMonitorRequest_Command) Descriptor() protoreflect.EnumDescriptor {
	return file_wearable_v1_wearable_service_proto_enumTypes[0].Descriptor()
}

func (LiveMonitorRequest_Command) Type() protoreflect.EnumType {
	return &file_wearable_v1_wearable_service_proto_enumTypes[0]
}

func (x LiveMonitorRequest_Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LiveMonitorRequest_Command.Descriptor instead.
func (LiveMonitorRequest_Command) EnumDescriptor() ([]byte, []int) {
	return file_wearable_v1_wearable_service_proto_rawDescGZIP(), []int{6, 0}
}

type GetDeviceInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceInfoRequest) Reset() {
	*x = GetDeviceInfoRequest{}
	mi := &file_wearable_v1_wearable_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceInfoRequest) ProtoMessage() {}

func (x *GetDeviceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wearable_v1_wearable_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceInfoRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceInfoRequest) Descriptor() ([]byte, []int) {
	return file_wearable_v1_wearable_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetDeviceInfoRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetDeviceInfoResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Uuid              string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BatteryPercentage uint32                 `protobuf:"varint,3,opt,name=battery_percentage,json=batteryPercentage,proto3" json:"battery_percentage,omitempty"`
	FirmwareVersion   string                 `protobuf:"bytes,4,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetDeviceInfoResponse) Reset() {
	*x = GetDeviceInfoResponse{}
	mi := &file_wearable_v1_wearable_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceInfoResponse) ProtoMessage() {}

func (x *GetDeviceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wearable_v1_wearable_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceInfoResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceInfoResponse) Descriptor() ([]byte, []int) {
	return file_wearable_v1_wearable_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetDeviceInfoResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetDeviceInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDeviceInfoResponse) GetBatteryPercentage() uint32 {
	if x != nil {
		return x.BatteryPercentage
	}
	return 0
}

func (x *GetDeviceInfoResponse) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

type BeatsPerMinuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeatsPerMinuteRequest) Reset() {
	*x = BeatsPerMinuteRequest{}
	mi := &file_wearable_v1_wearable_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeatsPerMinuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeatsPerMinuteRequest) ProtoMessage() {}

func (x *BeatsPerMinuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wearable_v1_wearable_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeatsPerMinuteRequest.ProtoReflect.Descriptor instead.
func (*BeatsPerMinuteRequest) Descriptor() ([]byte, []int) {
	return file_wearable_v1_wearable_service_proto_rawDescGZIP(), []int{2}
}

func (x *BeatsPerMinuteRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type BeatsPerMinuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         uint32                 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Minute        uint32                 `protobuf:"varint,2,opt,name=minute,proto3" json:"minute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeatsPerMinuteResponse) Reset() {
	*x = BeatsPerMinuteResponse{}
	mi := &file_wearable_v1_wearable_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeatsPerMinuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeatsPerMinuteResponse) ProtoMessage() {}

func (x *BeatsPerMinuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wearable_v1_wearable_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeatsPerMinuteResponse.ProtoReflect.Descriptor instead.
func (*BeatsPerMinuteResponse) Descriptor() ([]byte, []int) {
	return file_wearable_v1_wearable_service_proto_rawDescGZIP(), []int{3}
}

func (x *BeatsPerMinuteResponse) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *BeatsPerMinuteResponse) GetMinute() uint32 {
	if x != nil {
		return x.Minute
	}
	return 0
}

type HealthDataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Bpm           uint32                 `protobuf:"varint,2,opt,name=bpm,proto3" json:"bpm,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthDataPoint) Reset() {
	*x = HealthDataPoint{}
	mi := &file_wearable_v1_wearable_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthDataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthDataPoint) ProtoMessage() {}

func (x *HealthDataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_wearable_v1_wearable_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthDataPoint.ProtoReflect.Descriptor instead.
func (*HealthDataPoint) Descriptor() ([]byte, []int) {
	return file_wearable_v1_wearable_service_proto_rawDescGZIP(), []int{4}
}

func (x *HealthDataPoint) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *HealthDataPoint) GetBpm() uint32 {
	if x != nil {
		return x.Bpm
	}
	return 0
}

func (x *HealthDataPoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HealthDataSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalPoints   uint32                 `protobuf:"varint,1,opt,name=total_points,json=totalPoints,proto3" json:"total_points,omitempty"`
	AvgBpm        uint32                 `protobuf:"varint,2,opt,name=avg_bpm,json=avgBpm,proto3" json:"avg_bpm,omitempty"`
	MinBpm        uint32                 `protobuf:"varint,3,opt,name=min_bpm,json=minBpm,proto3" json:"min_bpm,omitempty"`
	MaxBpm        uint32                 `protobuf:"varint,4,opt,name=max_bpm,json=maxBpm,proto3" json:"max_bpm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthDataSummary) Reset() {
	*x = HealthDataSummary{}
	mi := &file_wearable_v1_wearable_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthDataSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthDataSummary) ProtoMessage() {}

func (x *HealthDataSummary) ProtoReflect() protoreflect.Message {
	mi := &file_wearable_v1_wearable_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthDataSummary.ProtoReflect.Descriptor instead.
func (*HealthDataSummary) Descriptor() ([]byte, []int) {
	return file_wearable_v1_wearable_service_proto_rawDescGZIP(), []int{5}
}

func (x *HealthDataSummary) GetTotalPoints() uint32 {
	if x != nil {
		return x.TotalPoints
	}
	return 0
}

func (x *HealthDataSummary) GetAvgBpm() uint32 {
	if x != nil {
		return x.AvgBpm
	}
	return 0
}

func (x *HealthDataSummary) GetMinBpm() uint32 {
	if x != nil {
		return x.MinBpm
	}
	return 0
}

func (x *HealthDataSummary) GetMaxBpm() uint32 {
	if x != nil {
		return x.MaxBpm
	}
	return 0
}

type LiveMonitorRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Command       LiveMonitorRequest_Command `protobuf:"varint,1,opt,name=command,proto3,enum=wearable.v1.LiveMonitorRequest_Command" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveMonitorRequest) Reset() {
	*x = LiveMonitorRequest{}
	mi := &file_wearable_v1_wearable_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveMonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveMonitorRequest) ProtoMessage() {}

func (x *LiveMonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wearable_v1_wearable_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveMonitorRequest.ProtoReflect.Descriptor instead.
func (*LiveMonitorRequest) Descriptor() ([]byte, []int) {
	return file_wearable_v1_wearable_service_proto_rawDescGZIP(), []int{6}
}

func (x *LiveMonitorRequest) GetCommand() LiveMonitorRequest_Command {
	if x != nil {
		return x.Command
	}
	return LiveMonitorRequest_START
}

type LiveMonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Bpm           uint32                 `protobuf:"varint,2,opt,name=bpm,proto3" json:"bpm,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveMonitorResponse) Reset() {
	*x = LiveMonitorResponse{}
	mi := &file_wearable_v1_wearable_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveMonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveMonitorResponse) ProtoMessage() {}

func (x *LiveMonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wearable_v1_wearable_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveMonitorResponse.ProtoReflect.Descriptor instead.
func (*LiveMonitorResponse) Descriptor() ([]byte, []int) {
	return file_wearable_v1_wearable_service_proto_rawDescGZIP(), []int{7}
}

func (x *LiveMonitorResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LiveMonitorResponse) GetBpm() uint32 {
	if x != nil {
		return x.Bpm
	}
	return 0
}

func (x *LiveMonitorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_wearable_v1_wearable_service_proto protoreflect.FileDescriptor

const file_wearable_v1_wearable_service_proto_rawDesc = "" +
	"\n" +
	"\"wearable/v1/wearable_service.proto\x12\vwearable.v1\x1a\x1cgoogle/api/annotations.proto\"*\n" +
	"\x14GetDeviceInfoRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x99\x01\n" +
	"\x15GetDeviceInfoResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x12battery_percentage\x18\x03 \x01(\rR\x11batteryPercentage\x12)\n" +
	"\x10firmware_version\x18\x04 \x01(\tR\x0ffirmwareVersion\"+\n" +
	"\x15BeatsPerMinuteRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"F\n" +
	"\x16BeatsPerMinuteResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\rR\x05value\x12\x16\n" +
	"\x06minute\x18\x02 \x01(\rR\x06minute\"U\n" +
	"\x0fHealthDataPoint\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x10\n" +
	"\x03bpm\x18\x02 \x01(\rR\x03bpm\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x81\x01\n" +
	"\x11HealthDataSummary\x12!\n" +
	"\ftotal_points\x18\x01 \x01(\rR\vtotalPoints\x12\x17\n" +
	"\aavg_bpm\x18\x02 \x01(\rR\x06avgBpm\x12\x17\n" +
	"\amin_bpm\x18\x03 \x01(\rR\x06minBpm\x12\x17\n" +
	"\amax_bpm\x18\x04 \x01(\rR\x06maxBpm\"\x82\x01\n" +
	"\x12LiveMonitorRequest\x12A\n" +
	"\acommand\x18\x01 \x01(\x0e2'.wearable.v1.LiveMonitorRequest.CommandR\acommand\")\n" +
	"\aCommand\x12\t\n" +
	"\x05START\x10\x00\x12\t\n" +
	"\x05PAUSE\x10\x01\x12\b\n" +
	"\x04STOP\x10\x02\"Y\n" +
	"\x13LiveMonitorResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x10\n" +
	"\x03bpm\x18\x02 \x01(\rR\x03bpm\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xc5\x03\n" +
	"\x0fWearableService\x12x\n" +
	"\rGetDeviceInfo\x12!.wearable.v1.GetDeviceInfoRequest\x1a\".wearable.v1.GetDeviceInfoResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/wearable/{uuid}/info\x12\x89\x01\n" +
	"\x0eBeatsPerMinute\x12\".wearable.v1.BeatsPerMinuteRequest\x1a#.wearable.v1.BeatsPerMinuteResponse\",\x82\xd3\xe4\x93\x02&\x12$/v1/wearable/{uuid}/beats-per-minute0\x01\x12T\n" +
	"\x10UploadHealthData\x12\x1c.wearable.v1.HealthDataPoint\x1a\x1e.wearable.v1.HealthDataSummary\"\x00(\x01\x12V\n" +
	"\vLiveMonitor\x12\x1f.wearable.v1.LiveMonitorRequest\x1a .wearable.v1.LiveMonitorResponse\"\x00(\x010\x01BEZCgithub.com/hypergadam/grpc-streaming/pkg/api/wearable/v1;wearablepbb\x06proto3"

var (
	file_wearable_v1_wearable_service_proto_rawDescOnce sync.Once
	file_wearable_v1_wearable_service_proto_rawDescData []byte
)

func file_wearable_v1_wearable_service_proto_rawDescGZIP() []byte {
	file_wearable_v1_wearable_service_proto_rawDescOnce.Do(func() {
		file_wearable_v1_wearable_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wearable_v1_wearable_service_proto_rawDesc), len(file_wearable_v1_wearable_service_proto_rawDesc)))
	})
	return file_wearable_v1_wearable_service_proto_rawDescData
}

var file_wearable_v1_wearable_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wearable_v1_wearable_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_wearable_v1_wearable_service_proto_goTypes = []any{
	(LiveMonitorRequest_Command)(0), // 0: wearable.v1.LiveMonitorRequest.Command
	(*GetDeviceInfoRequest)(nil),    // 1: wearable.v1.GetDeviceInfoRequest
	(*GetDeviceInfoResponse)(nil),   // 2: wearable.v1.GetDeviceInfoResponse
	(*BeatsPerMinuteRequest)(nil),   // 3: wearable.v1.BeatsPerMinuteRequest
	(*BeatsPerMinuteResponse)(nil),  // 4: wearable.v1.BeatsPerMinuteResponse
	(*HealthDataPoint)(nil),         // 5: wearable.v1.HealthDataPoint
	(*HealthDataSummary)(nil),       // 6: wearable.v1.HealthDataSummary
	(*LiveMonitorRequest)(nil),      // 7: wearable.v1.LiveMonitorRequest
	(*LiveMonitorResponse)(nil),     // 8: wearable.v1.LiveMonitorResponse
}
var file_wearable_v1_wearable_service_proto_depIdxs = []int32{
	0, // 0: wearable.v1.LiveMonitorRequest.command:type_name -> wearable.v1.LiveMonitorRequest.Command
	1, // 1: wearable.v1.WearableService.GetDeviceInfo:input_type -> wearable.v1.GetDeviceInfoRequest
	3, // 2: wearable.v1.WearableService.BeatsPerMinute:input_type -> wearable.v1.BeatsPerMinuteRequest
	5, // 3: wearable.v1.WearableService.UploadHealthData:input_type -> wearable.v1.HealthDataPoint
	7, // 4: wearable.v1.WearableService.LiveMonitor:input_type -> wearable.v1.LiveMonitorRequest
	2, // 5: wearable.v1.WearableService.GetDeviceInfo:output_type -> wearable.v1.GetDeviceInfoResponse
	4, // 6: wearable.v1.WearableService.BeatsPerMinute:output_type -> wearable.v1.BeatsPerMinuteResponse
	6, // 7: wearable.v1.WearableService.UploadHealthData:output_type -> wearable.v1.HealthDataSummary
	8, // 8: wearable.v1.WearableService.LiveMonitor:output_type -> wearable.v1.LiveMonitorResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wearable_v1_wearable_service_proto_init() }
func file_wearable_v1_wearable_service_proto_init() {
	if File_wearable_v1_wearable_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wearable_v1_wearable_service_proto_rawDesc), len(file_wearable_v1_wearable_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wearable_v1_wearable_service_proto_goTypes,
		DependencyIndexes: file_wearable_v1_wearable_service_proto_depIdxs,
		EnumInfos:         file_wearable_v1_wearable_service_proto_enumTypes,
		MessageInfos:      file_wearable_v1_wearable_service_proto_msgTypes,
	}.Build()
	File_wearable_v1_wearable_service_proto = out.File
	file_wearable_v1_wearable_service_proto_goTypes = nil
	file_wearable_v1_wearable_service_proto_depIdxs = nil
}
