// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.4
// source: wearable/v1/wearable_service.proto

package wearablepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WearableService_GetDeviceInfo_FullMethodName    = "/wearable.v1.WearableService/GetDeviceInfo"
	WearableService_BeatsPerMinute_FullMethodName   = "/wearable.v1.WearableService/BeatsPerMinute"
	WearableService_UploadHealthData_FullMethodName = "/wearable.v1.WearableService/UploadHealthData"
	WearableService_LiveMonitor_FullMethodName      = "/wearable.v1.WearableService/LiveMonitor"
)

// WearableServiceClient is the client API for WearableService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WearableServiceClient interface {
	// ─────────────────────────────────────────────────────
	// TYPE 1: UNARY
	// One request → One response. Classic HTTP-style call.
	// Use case: fetch static device info once.
	// ─────────────────────────────────────────────────────
	GetDeviceInfo(ctx context.Context, in *GetDeviceInfoRequest, opts ...grpc.CallOption) (*GetDeviceInfoResponse, error)
	// ─────────────────────────────────────────────────────
	// TYPE 2: SERVER STREAMING
	// One request → stream of responses.
	// Use case: client subscribes to live heart rate feed.
	//
	//	Server pushes a reading every second.
	//
	// ─────────────────────────────────────────────────────
	BeatsPerMinute(ctx context.Context, in *BeatsPerMinuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BeatsPerMinuteResponse], error)
	// ─────────────────────────────────────────────────────
	// TYPE 3: CLIENT STREAMING
	// Stream of requests → One response.
	// Use case: wearable uploads a batch of health data
	//
	//	collected offline. Server processes all of
	//	it and returns a single summary at the end.
	//
	// ─────────────────────────────────────────────────────
	UploadHealthData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HealthDataPoint, HealthDataSummary], error)
	// ─────────────────────────────────────────────────────
	// TYPE 4: BIDIRECTIONAL STREAMING
	// Stream of requests ↔ Stream of responses.
	// Use case: live interactive session. Client sends
	//
	//	commands (START/PAUSE/STOP), server streams
	//	real-time readings back while active.
	//
	// ─────────────────────────────────────────────────────
	LiveMonitor(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LiveMonitorRequest, LiveMonitorResponse], error)
}

type wearableServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWearableServiceClient(cc grpc.ClientConnInterface) WearableServiceClient {
	return &wearableServiceClient{cc}
}

func (c *wearableServiceClient) GetDeviceInfo(ctx context.Context, in *GetDeviceInfoRequest, opts ...grpc.CallOption) (*GetDeviceInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceInfoResponse)
	err := c.cc.Invoke(ctx, WearableService_GetDeviceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wearableServiceClient) BeatsPerMinute(ctx context.Context, in *BeatsPerMinuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BeatsPerMinuteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WearableService_ServiceDesc.Streams[0], WearableService_BeatsPerMinute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BeatsPerMinuteRequest, BeatsPerMinuteResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WearableService_BeatsPerMinuteClient = grpc.ServerStreamingClient[BeatsPerMinuteResponse]

func (c *wearableServiceClient) UploadHealthData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HealthDataPoint, HealthDataSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WearableService_ServiceDesc.Streams[1], WearableService_UploadHealthData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HealthDataPoint, HealthDataSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WearableService_UploadHealthDataClient = grpc.ClientStreamingClient[HealthDataPoint, HealthDataSummary]

func (c *wearableServiceClient) LiveMonitor(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LiveMonitorRequest, LiveMonitorResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WearableService_ServiceDesc.Streams[2], WearableService_LiveMonitor_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LiveMonitorRequest, LiveMonitorResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WearableService_LiveMonitorClient = grpc.BidiStreamingClient[LiveMonitorRequest, LiveMonitorResponse]

// WearableServiceServer is the server API for WearableService service.
// All implementations must embed UnimplementedWearableServiceServer
// for forward compatibility.
type WearableServiceServer interface {
	// ─────────────────────────────────────────────────────
	// TYPE 1: UNARY
	// One request → One response. Classic HTTP-style call.
	// Use case: fetch static device info once.
	// ─────────────────────────────────────────────────────
	GetDeviceInfo(context.Context, *GetDeviceInfoRequest) (*GetDeviceInfoResponse, error)
	// ─────────────────────────────────────────────────────
	// TYPE 2: SERVER STREAMING
	// One request → stream of responses.
	// Use case: client subscribes to live heart rate feed.
	//
	//	Server pushes a reading every second.
	//
	// ─────────────────────────────────────────────────────
	BeatsPerMinute(*BeatsPerMinuteRequest, grpc.ServerStreamingServer[BeatsPerMinuteResponse]) error
	// ─────────────────────────────────────────────────────
	// TYPE 3: CLIENT STREAMING
	// Stream of requests → One response.
	// Use case: wearable uploads a batch of health data
	//
	//	collected offline. Server processes all of
	//	it and returns a single summary at the end.
	//
	// ─────────────────────────────────────────────────────
	UploadHealthData(grpc.ClientStreamingServer[HealthDataPoint, HealthDataSummary]) error
	// ─────────────────────────────────────────────────────
	// TYPE 4: BIDIRECTIONAL STREAMING
	// Stream of requests ↔ Stream of responses.
	// Use case: live interactive session. Client sends
	//
	//	commands (START/PAUSE/STOP), server streams
	//	real-time readings back while active.
	//
	// ─────────────────────────────────────────────────────
	LiveMonitor(grpc.BidiStreamingServer[LiveMonitorRequest, LiveMonitorResponse]) error
	mustEmbedUnimplementedWearableServiceServer()
}

// UnimplementedWearableServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWearableServiceServer struct{}

func (UnimplementedWearableServiceServer) GetDeviceInfo(context.Context, *GetDeviceInfoRequest) (*GetDeviceInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceInfo not implemented")
}
func (UnimplementedWearableServiceServer) BeatsPerMinute(*BeatsPerMinuteRequest, grpc.ServerStreamingServer[BeatsPerMinuteResponse]) error {
	return status.Errorf(codes.Unimplemented, "method BeatsPerMinute not implemented")
}
func (UnimplementedWearableServiceServer) UploadHealthData(grpc.ClientStreamingServer[HealthDataPoint, HealthDataSummary]) error {
	return status.Errorf(codes.Unimplemented, "method UploadHealthData not implemented")
}
func (UnimplementedWearableServiceServer) LiveMonitor(grpc.BidiStreamingServer[LiveMonitorRequest, LiveMonitorResponse]) error {
	return status.Errorf(codes.Unimplemented, "method LiveMonitor not implemented")
}
func (UnimplementedWearableServiceServer) mustEmbedUnimplementedWearableServiceServer() {}
func (UnimplementedWearableServiceServer) testEmbeddedByValue()                         {}

// UnsafeWearableServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WearableServiceServer will
// result in compilation errors.
type UnsafeWearableServiceServer interface {
	mustEmbedUnimplementedWearableServiceServer()
}

func RegisterWearableServiceServer(s grpc.ServiceRegistrar, srv WearableServiceServer) {
	// If the following call pancis, it indicates UnimplementedWearableServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WearableService_ServiceDesc, srv)
}

func _WearableService_GetDeviceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WearableServiceServer).GetDeviceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WearableService_GetDeviceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WearableServiceServer).GetDeviceInfo(ctx, req.(*GetDeviceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WearableService_BeatsPerMinute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BeatsPerMinuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WearableServiceServer).BeatsPerMinute(m, &grpc.GenericServerStream[BeatsPerMinuteRequest, BeatsPerMinuteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WearableService_BeatsPerMinuteServer = grpc.ServerStreamingServer[BeatsPerMinuteResponse]

func _WearableService_UploadHealthData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WearableServiceServer).UploadHealthData(&grpc.GenericServerStream[HealthDataPoint, HealthDataSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WearableService_UploadHealthDataServer = grpc.ClientStreamingServer[HealthDataPoint, HealthDataSummary]

func _WearableService_LiveMonitor_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WearableServiceServer).LiveMonitor(&grpc.GenericServerStream[LiveMonitorRequest, LiveMonitorResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WearableService_LiveMonitorServer = grpc.BidiStreamingServer[LiveMonitorRequest, LiveMonitorResponse]

// WearableService_ServiceDesc is the grpc.ServiceDesc for WearableService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WearableService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wearable.v1.WearableService",
	HandlerType: (*WearableServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeviceInfo",
			Handler:    _WearableService_GetDeviceInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BeatsPerMinute",
			Handler:       _WearableService_BeatsPerMinute_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadHealthData",
			Handler:       _WearableService_UploadHealthData_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "LiveMonitor",
			Handler:       _WearableService_LiveMonitor_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "wearable/v1/wearable_service.proto",
}
